### ISSUE TITLE
Node Modules in the Main Repository

### ISSUE THREAD

**Issue by VictorSCushman** [QuickCorp/QCObjects#2]
Purpose: The `node_modules` directory exists within the main repository. This directory contains a whopping 18 megabytes of content which (a) makes the repository unnecessarily large causing which may lead to clone / push / pull problems in areas with restricted bandwidth and (b) is a security vulnerability if the integrity of the directory is not validated after cloning / pulling. It is considered best practice to *not* include `node_modules` in a repository and instead let the end user pull from npm themselves.

Feature: Remove the `node_modules` directory from the repository.

Artifact: N/A

Priority: Low

Changes:
1. Add `node_modules` to the project `.gitignore`.
2. Delete the current `node_modules` directory from the repository.

**Comment by jeanmachuca** [comment]
Thanks @VictorSCushman , It's been removed following the guidelines of @lmcneel
here  https://gist.github.com/lmcneel/45594e550a3403d589bdcaad38138a83
